config/routes.rb
Rails.application.routes.draw do
  resources :admins do
    resources :zones do
      resources :orphanages do
        resources :students
      end
    end
  end

  get '/zones/:id/get_all_orphanages'=>"zones#get_all_orphanages"

  resources :zones
  resources :orphanages
  devise_for :users
  resources :students

  authenticated :user do
    root "orphanages#index", as: "authenticated_root"
  end

  root "welcome#index"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      get '/get_orphanages_list' => "orphanage#get_orphanages_list"
      get '/get_orphanage_students/:id' => "orphanage#get_orphanage_students"

    end
  end
end

app/models/orphanage.rb
class Orphanage < User
  belongs_to :zone
  belongs_to :admin
  has_many :students

  validates_presence_of :zone_id

end

app/controllers/api/v1/orphanage_controller.rb
class Api::V1::OrphanageController < Api::V1::BaseController
  respond_to :json


  def get_orphanages_list
    @orphanages = Orphanage.all
    respond_with @orphanages

  end

  def get_orphanage_students
    @students = Orphanage.find(params[:id]).students.all
    respond_with @students
  end

end

app/controllers/orphanages_controller.rb
class OrphanagesController < ApplicationController
  before_action :set_orphanage, only: [:show, :edit, :update, :destroy]

  # GET /orphanages
  # GET /orphanages.json
  def index
    @orphanages = Orphanage.all
  end

  # GET /orphanages/1
  # GET /orphanages/1.json
  def show
    @students = @orphanage.students.all
  end

  # GET /orphanages/new
  def new
    @orphanage = Orphanage.new
  end

  # GET /orphanages/1/edit
  def edit
  end

  # POST /orphanages
  # POST /orphanages.json
  def create
    @orphanage = Orphanage.new(orphanage_params)

    respond_to do |format|
      if @orphanage.save
        format.html { redirect_to @orphanage, notice: 'Orphanage was successfully created.' }
        format.json { render :show, status: :created, location: @orphanage }
      else
        format.html { render :new }
        format.json { render json: @orphanage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orphanages/1
  # PATCH/PUT /orphanages/1.json
  def update
    respond_to do |format|
      if @orphanage.update(orphanage_params)
        format.html { redirect_to @orphanage, notice: 'Orphanage was successfully updated.' }
        format.json { render :show, status: :ok, location: @orphanage }
      else
        format.html { render :edit }
        format.json { render json: @orphanage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orphanages/1
  # DELETE /orphanages/1.json
  def destroy
    @orphanage.destroy
    respond_to do |format|
      format.html { redirect_to orphanages_url, notice: 'Orphanage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orphanage
      @orphanage = Orphanage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orphanage_params
      params.require(:orphanage).permit(:first_name, :last_name, :address, :phone_no, :email, :password, :zone_id)
    end
end

app/helpers/orphanages_helper.rb
module OrphanagesHelper
end

app/views/orphanages/_form.html.erb
<%= form_for(@orphanage) do |f| %>
    <% if @orphanage.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@orphanage.errors.count, "error") %> prohibited this orphanage from being saved:</h2>

          <ul>
            <% @orphanage.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <h2>Create Orphanage</h2>

    <%= f.collection_select :zone_id, Zone.all,:id,:email, include_blank: false %>


    <div><%= f.label :first_name %><br />
      <%= f.text_field :first_name, autofocus: true %></div>

    <div><%= f.label :last_name %><br />
      <%= f.text_field :last_name, autofocus: true %></div>

    <div><%= f.label :address %><br />
      <%= f.text_field :address, autofocus: true %></div>

    <div><%= f.label :phone_no %><br />
      <%= f.text_field :phone_no, autofocus: true %></div>


    <div><%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true %></div>

    <div><%= f.label :password %> <% if @validatable %><i>(<%= @minimum_password_length %> characters minimum)</i><% end %><br />
      <%= f.password_field :password, autocomplete: "off" %></div>

    <div><%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %></div>
    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>

app/views/orphanages/edit.html.erb
<h1>Editing Orphanage</h1>

<%= render 'form' %>

<%= link_to 'Show', @orphanage %> |
<%= link_to 'Back', orphanages_path %>

app/views/orphanages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orphanages</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Orphanage</th>
    <th>Email</th>
    <th>Number of Students</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @orphanages.each do |orphanage| %>
      <tr>
        <td><%= link_to orphanage.first_name, orphanage %></td>
        <td><%= orphanage.email %></td>
        <td><%= orphanage.students.count %></td>
        <td><%= link_to 'Show', orphanage %></td>
        <% if can? :update, orphanage %>
            <td><%= link_to 'Edit', edit_orphanage_path(orphanage) %></td>
        <% end %>
        <% if current_user.type == 'Zone' || current_user.type == 'Admin' %>
            <td><%= link_to 'Destroy', orphanage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Orphanage', new_orphanage_path %>

app/views/orphanages/new.html.erb
<h1>New Orphanage</h1>

<%= render 'form' %>

<%= link_to 'Back', orphanages_path %>

app/views/orphanages/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @orphanage.first_name %></h3>
<br>


<%= link_to 'Edit', edit_orphanage_path(@orphanage) %> |
<%= link_to 'Back', orphanages_path %>
<br><br>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Student Name</th>
    <th>Class</th>
    <th>Gender</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.name, student %></td>
        <td><%= student.kaksha %></td>
        <td><%= student.gender %></td>
        <td><%= link_to 'Show', student %></td>

        <% if can? :update, @orphanage %>
            <td><%= link_to 'Edit', edit_student_path(student) %></td>
            <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

      </tr>
  <% end %>
  </tbody>
</table>