config/routes.rb
Rails.application.routes.draw do
  resources :admins do
    resources :zones do
      resources :orphanages do
        resources :students
      end
    end
  end

  get '/zones/:id/get_all_orphanages'=>"zones#get_all_orphanages"

  resources :zones
  resources :orphanages
  devise_for :users
  resources :students

  authenticated :user do
    root "orphanages#index", as: "authenticated_root"
  end

  root "welcome#index"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      get '/get_orphanages_list' => "orphanage#get_orphanages_list"
      get '/get_orphanage_students/:id' => "orphanage#get_orphanage_students"

    end
  end
end

app/models/zone.rb
class Zone < User
  belongs_to :admin
  has_many :orphanages
  has_many :students


end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_action :set_zone, only: [:show, :edit, :update, :destroy, :get_all_orphanages]

  # GET /zones
  # GET /zones.json
  def index
    @zones = Zone.all
  end

  # GET /zones/1
  # GET /zones/1.json
  def show
    @orphanages = @zone.orphanages.all
  end

  # GET /zones/new
  def new
    @zone = Zone.new
  end

  # GET /zones/1/edit
  def edit
  end

  # POST /zones
  # POST /zones.json
  def create
    @zone = Zone.new(zone_params)

    respond_to do |format|
      if @zone.save
        format.html { redirect_to @zone, notice: 'Zone was successfully created.' }
        format.json { render :show, status: :created, location: @zone }
      else
        format.html { render :new }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zones/1
  # PATCH/PUT /zones/1.json
  def update
    respond_to do |format|
      if @zone.update(zone_params)
        format.html { redirect_to @zone, notice: 'Zone was successfully updated.' }
        format.json { render :show, status: :ok, location: @zone }
      else
        format.html { render :edit }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zones/1
  # DELETE /zones/1.json
  def destroy
    @zone.destroy
    respond_to do |format|
      format.html { redirect_to zones_url, notice: 'Zone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_all_orphanages
    @orphanages = @zone.orphanages.map{|u| Hash[value: "#{u.id}", name: u.email]}
    render json:@orphanages
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zone
      @zone = Zone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zone_params
      params.require(:zone).permit(:email, :password, :password_confirmation, :first_name, :last_name, :address, :phone_no)
    end
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/zones/_form.html.erb
<%= form_for(@zone) do |f| %>
    <% if @zone.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@zone.errors.count, "error") %> prohibited this zone from being saved:</h2>

          <ul>
            <% @zone.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div><%= f.label :first_name %><br />
      <%= f.text_field :first_name, autofocus: true %></div>

    <div><%= f.label :last_name %><br />
      <%= f.text_field :last_name, autofocus: true %></div>

    <div><%= f.label :address %><br />
      <%= f.text_field :address, autofocus: true %></div>

    <div><%= f.label :phone_no %><br />
      <%= f.text_field :phone_no, autofocus: true %></div>

    <div><%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true %></div>

    <div><%= f.label :password %> <% if @validatable %><i>(<%= @minimum_password_length %> characters minimum)</i><% end %><br />
      <%= f.password_field :password, autocomplete: "off" %></div>

    <div><%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %></div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/zones/edit.html.erb
<h1>Editing Zone</h1>

<%= render 'form' %>

<%= link_to 'Show', @zone %> |
<%= link_to 'Back', zones_path %>

app/views/zones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Zones</h1>
<br>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Number of Orphanages</th>
  </tr>
  </thead>

  <tbody>
  <% @zones.each do |zone| %>
      <tr>
        <td><%= link_to zone.first_name, zone %></td>
        <td><%= zone.email %></td>
        <td><%= zone.orphanages.count %></td>

        <td><%= link_to 'Show', zone %></td>
        <% if can? :update, zone %>
            <td><%= link_to 'Edit', edit_zone_path(zone) %></td>
        <% end %>
        <% if current_user.type == 'Admin' %>
            <td><%= link_to 'Destroy', zone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zone', new_zone_path %>

app/views/zones/new.html.erb
<h1>New Zone</h1>

<%= render 'form' %>

<%= link_to 'Back', zones_path %>

app/views/zones/show.html.erb
<p id="notice"><%= notice %></p>
<h3><%= @zone.first_name %></h3>
<br>
<%= link_to 'Edit', edit_zone_path(@zone) %> |
<%= link_to 'Back', zones_path %>

<br><br>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Orphanage Name</th>
    <th>Email</th>
    <th>Contact Number</th>
    <th>Number of Students</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @orphanages.each do |orphanage| %>
      <tr>
        <td><%= link_to orphanage.first_name, orphanage %></td>
        <td><%= orphanage.email %></td>
        <td><%= orphanage.phone_no %></td>
        <td><%= orphanage.students.count %></td>
        <td><%= link_to 'Show', orphanage %></td>
        <% if current_user.type == 'Zone' || current_user.type == 'Admin' %>
            <td><%= link_to 'Edit', edit_orphanage_path(orphanage) %></td>
            <td><%= link_to 'Destroy', orphanage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>


      </tr>
  <% end %>
  </tbody>
</table>