config/routes.rb
Rails.application.routes.draw do
  resources :admins do
    resources :zones do
      resources :orphanages do
        resources :students
      end
    end
  end

  get '/zones/:id/get_all_orphanages'=>"zones#get_all_orphanages"

  resources :zones
  resources :orphanages
  devise_for :users
  resources :students

  authenticated :user do
    root "orphanages#index", as: "authenticated_root"
  end

  root "welcome#index"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      get '/get_orphanages_list' => "orphanage#get_orphanages_list"
      get '/get_orphanage_students/:id' => "orphanage#get_orphanage_students"

    end
  end
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Helping Hands
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Helping Hands", root_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          - if current_user.type == 'Admin'
            %li= link_to "New Zone", new_zone_path
          - if current_user.type == 'Admin' or 'Zone'
            %li= link_to "New Orphanage", new_orphanage_path
          %li= link_to "New Student", new_student_path
          %li= link_to "Zones", zones_path
          %li= link_to "Orphanages", orphanages_path
          %li= link_to "Students", students_path
          %li= link_to "Account", edit_user_registration_path
          %li= link_to "Sign out", destroy_user_session_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign In", new_user_session_path
  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"
    = yield

  %footer.navbar-fixed-bottom
    %p &copy; Helping Hands